### ISSUE TITLE
快去使用replaceFragment()报错

### ISSUE THREAD

**Issue by eternallyjie** [weikaiyun/SFragmentation#11]
当我在activity里面快去使用replaceFragment()切换fragment的时候，报错闪退，报错信息如下：

java.lang.IllegalStateException: Fragment no longer exists for key f0: unique id 899f341a-97bd-458a-85a7-d76e5a515333
        at androidx.fragment.app.FragmentManager.getFragment(FragmentManager.java:960)
        at androidx.fragment.app.FragmentStatePagerAdapter.restoreState(FragmentStatePagerAdapter.java:328)
        at androidx.viewpager.widget.ViewPager.onRestoreInstanceState(ViewPager.java:1461)
        at android.view.View.dispatchRestoreInstanceState(View.java:15805)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3274)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3282)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3282)
        at android.view.View.restoreHierarchyState(View.java:15783)
        at androidx.fragment.app.Fragment.restoreViewState(Fragment.java:636)
        at androidx.fragment.app.Fragment.restoreViewState(Fragment.java:2997)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2988)
        at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:577)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2177)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2088)
        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1959)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:311)
        at com.weikaiyun.fragmentation.j.a(TransactionDelegate.java:496)
        at com.weikaiyun.fragmentation.j.b(TransactionDelegate.java:457)
        at com.weikaiyun.fragmentation.j.b(TransactionDelegate.java:394)
        at com.weikaiyun.fragmentation.j.a(TransactionDelegate.java:23)
        at com.weikaiyun.fragmentation.j$d.a(TransactionDelegate.java:143)
        at com.weikaiyun.fragmentation.k.b.a(ActionQueue.java:46)
        at com.weikaiyun.fragmentation.k.b.b(ActionQueue.java:37)
        at com.weikaiyun.fragmentation.k.b.a(ActionQueue.java:9)
        at com.weikaiyun.fragmentation.k.b$a.run(ActionQueue.java:29)
        at android.os.Handler.handleCallback(Handler.java:761)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6623)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by eternallyjie** [comment]
快速使用replaceFragment()切换fragment。fragmentation库同样有这个问题。

**Comment by weikaiyun** [comment]
能fork一下仓库，把代码推上来看看嘛

**Comment by weikaiyun** [comment]
你可以fork一下仓库，把报错的demo推上来， 我看看。
