### ISSUE TITLE
回退栈只有一个的情况pop有问题

### ISSUE THREAD

**Issue by zwonb** [weikaiyun/SFragmentation#12]
回退栈只有一个的情况pop有问题，fragmention处理是关闭activity

**Comment by weikaiyun** [comment]
回退栈只有一个 SFragmentation是什么情况，现在有什么问题呢

**Comment by zwonb** [comment]
java.lang.NullPointerException: Attempt to invoke interface method 'com.weikaiyun.fragmentation.SupportFragmentDelegate com.weikaiyun.fragmentation.ISupportFragment.getSupportDelegate()' on a null object reference
&nbsp; &nbsp; &nbsp; &nbsp; at com.weikaiyun.fragmentation.TransactionDelegate$12.run(TransactionDelegate.java:251)
&nbsp; &nbsp; &nbsp; &nbsp; at com.weikaiyun.fragmentation.queue.ActionQueue.handleAction(ActionQueue.java:46)
&nbsp; &nbsp; &nbsp; &nbsp; at com.weikaiyun.fragmentation.queue.ActionQueue.enqueueAction(ActionQueue.java:37)
&nbsp; &nbsp; &nbsp; &nbsp; at com.weikaiyun.fragmentation.queue.ActionQueue.access$000(ActionQueue.java:9)
&nbsp; &nbsp; &nbsp; &nbsp; at com.weikaiyun.fragmentation.queue.ActionQueue$1.run(ActionQueue.java:29)
&nbsp; &nbsp; &nbsp; &nbsp; at android.os.Handler.handleCallback(Handler.java:761)
&nbsp; &nbsp; &nbsp; &nbsp; at android.os.Handler.dispatchMessage(Handler.java:98)
&nbsp; &nbsp; &nbsp; &nbsp; at android.os.Looper.loop(Looper.java:156)
&nbsp; &nbsp; &nbsp; &nbsp; at android.app.ActivityThread.main(ActivityThread.java:6623)
&nbsp; &nbsp; &nbsp; &nbsp; at java.lang.reflect.Method.invoke(Native Method)
&nbsp; &nbsp; &nbsp; &nbsp; at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
&nbsp; &nbsp; &nbsp; &nbsp; at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月27日(星期二) 上午10:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [weikaiyun/SFragmentation] 回退栈只有一个的情况pop有问题 (#12)





 
回退栈只有一个 SFragmentation是什么情况，现在有什么问题呢

**Comment by zwonb** [comment]
`java.lang.NullPointerException: Attempt to invoke interface method 'com.weikaiyun.fragmentation.SupportFragmentDelegate com.weikaiyun.fragmentation.ISupportFragment.getSupportDelegate()' on a null object reference
        at com.weikaiyun.fragmentation.TransactionDelegate$12.run(TransactionDelegate.java:251)
        at com.weikaiyun.fragmentation.queue.ActionQueue.handleAction(ActionQueue.java:46)
        at com.weikaiyun.fragmentation.queue.ActionQueue.enqueueAction(ActionQueue.java:37)
        at com.weikaiyun.fragmentation.queue.ActionQueue.access$000(ActionQueue.java:9)
        at com.weikaiyun.fragmentation.queue.ActionQueue$1.run(ActionQueue.java:29)
        at android.os.Handler.handleCallback(Handler.java:761)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6623)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)`

**Comment by weikaiyun** [comment]
你可以fork一下， 把demo推上来我看看吗

**Comment by weikaiyun** [comment]
或者你把你的代码截个图，我看看你是咋使用的

**Comment by zwonb** [comment]
![QQ图片20210427100800](https://user-images.githubusercontent.com/22101549/116174174-7d7cab80-a740-11eb-9d27-506ccd0e0ad6.png)

**Comment by weikaiyun** [comment]
是有点问题，我修复下。

**Comment by weikaiyun** [comment]
若是activity中只有一个fragment， 请直接使用_mActivity.finish(),  此时不应直接使用pop(), 新版本在调用pop()时做了null check。
